### ISSUE TITLE
Cannot Download SMPL models

### ISSUE THREAD

**Issue by muhabdulhaq** [nv-tlabs/vid2player3d#1]
Cannot Download SMPL models, only blank page shown.

**Comment by muhabdulhaq** [comment]
Thank you. I just need to register via this link https://smpl.is.tue.mpg.de/login.php

**Comment by Muksaki** [comment]
Hello, may I ask how did you solve this? Cause I'm running into blank page too, and it remains the same even if I've already registered.

**Comment by muhabdulhaq** [comment]
Access this https://download.is.tue.mpg.de/download.php?domain=smpl&sfile=SMPL_python_v.1.0.0.zip
Or access https://smpl.is.tue.mpg.de/download.php then click this link
![image](https://github.com/nv-tlabs/vid2player3d/assets/15086386/96e288c6-8d7a-4ec7-89bb-a142c065e111)

**Comment by Muksaki** [comment]
Thank you! I've been able to download this file now!
