### ISSUE TITLE
Checkpoints of motion VAE

### ISSUE THREAD

**Issue by muhabdulhaq** [nv-tlabs/vid2player3d#2]
Can you show me the format data of file latest.rar in vid2player3d/results ?

**Comment by Haotianz94** [comment]
It is in the format of a state dict saved by pytorch. [Here ](https://github.com/nv-tlabs/vid2player3d/blob/d9e95c17cc34b16d38b12f7e8fd5a4e325fb3361/vid2player/motion_vae/base.py#L271) is how a checkpoint is saved.
