### ISSUE TITLE
How to calculate global root position

### ISSUE THREAD

**Issue by Muksaki** [nv-tlabs/vid2player3d#5]
Thank you for sharing your work!
Could you give a more detailed description of how to calculate the global root positions? Did you apply GLAMR or made some modifications?

**Comment by Haotianz94** [comment]
For more details, please refer to Section 4 paragraph "Global root trajectory and camera estimation". 
Basically, we first estimate coarse global root trajectories using the estimated camera projection. Then we optimize the trajectory with the solution from GLAMR using the reprojection loss. Finally and most importantly, we still have to rely on the physics imitation to correct the noisy root trajectory.

**Comment by Muksaki** [comment]
Thank you for your answer! Furthermore, how do you decide the intrinsic parameters of camera when solving PNP problem to get the camera projection? Did it come from somewhat tennis official data?

**Comment by Haotianz94** [comment]
For the intrinsic matrix K, I set F_x = F_y = max(img_height, img_width) and the offset Ox = img_width / 2, O_y = img_height / 2.
I find this approximation works reasonably when solving PNP.
