### ISSUE TITLE
The data format of AMASS dataset

### ISSUE THREAD

**Issue by Z2HENG** [nv-tlabs/vid2player3d#6]
Hi, thanks for sharing your work！

I noticed that in the [convert_amass_isaac.py](https://github.com/nv-tlabs/vid2player3d/blob/main/uhc/utils/convert_amass_isaac.py), the format of AMASS data (amass_copycat_take5_5.pkl) differs from what is officially provided (e.g. A1 - Stand_poses.npz).

Could you please explain what changes were made to the original npz files? thanks！

**Comment by Haotianz94** [comment]
In the conversion script, we are essentially just using pose_aa, trans, beta and gender. For trans, beta and gender, you should be able to find the values from the original format with the same name. For pose_aa, it is the concatenation between root_orient and pose_body from the original format, which are the smpl pose parameters for these joints.

**Comment by Z2HENG** [comment]
> In the conversion script, we are essentially just using pose_aa, trans, beta and gender. For trans, beta and gender, you should be able to find the values from the original format with the same name. For pose_aa, it is the concatenation between root_orient and pose_body from the original format, which are the smpl pose parameters for these joints.

Thanks for your kind reply！

**Comment by jiho314** [comment]
Hi, thanks for great work! I'm trying to reproduce this work in mujoco.

Is this repo using preprocessing codes from UHC? (process_amass_db.py)
https://github.com/ZhengyiLuo/UniversalHumanoidControl?tab=readme-ov-file

I found out that the output format seems similar!
