### ISSUE TITLE
Preprocessing code for amass dataset

### ISSUE THREAD

**Issue by jihopark00** [nv-tlabs/vid2player3d#7]
Hi, thanks for great work! I'm trying to reproduce this work in mujoco.

Is this repo using preprocessing codes from UHC? (process_amass_db.py)
https://github.com/ZhengyiLuo/UniversalHumanoidControl?tab=readme-ov-file

I found out that the output format seems similar!

Thanks a lot!

**Comment by Haotianz94** [comment]
Yes, it is using the same preprocessing code.

**Comment by jihopark00** [comment]
Great! Thank you for your kind response!
